name: Generate PowerShell Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**/*.ps1'
      - 'modules/**/*.psm1'
      - 'modules/**/*.psd1'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**/*.ps1'
      - 'modules/**/*.psm1'
      - 'modules/**/*.psd1'
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    uses: ntatschner/tcs-shared-workflows/.github/workflows/powershell-docs.yml@main
    with:
      module_name: 'tcs.intune.packaging'
      module_path: 'modules/tcs.intune.packaging'
